platform :ios, '14.0'

# source 'git@github.com:leoilab/imagine_specs.git'
source 'https://cdn.cocoapods.org/'
source 'https://github.com/leoilab/mobile-sdk-distribution'

inhibit_all_warnings!
use_frameworks!

target 'ImageOutlineExample' do
  pod 'ImageOutlineClient', '~> 1.0'
end

target 'SuitabilityPredictionExample' do
  pod 'SuitabilityPredictionClient', '~> 1.0'
end

post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
           config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
           config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            end
         end
     end
  end
